package week10;

/**
 * Order Class.  Orders are generated by the warehouse, and couriers deliver the orders.
 */
public class Order {
    
    public int number; //order number
    public String description; //order description

    /**
     * Order constructor
     * @param integer order number
     * @param description order description
     */
    public Order(int integer, String description) {
        this.number = integer;
        this.description = description;
    }

    /**
     * Print Order Details
     * @return string to print
     */
    public String print() {
        return "Order number " + Integer.toString(this.number) + ": " + this.description;
    }

}
